# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.4
  aws-ecs: circleci/aws-ecs@0.0.3
  azure-cli: circleci/azure-cli@1.1.0
  clair-scanner: ovotech/clair-scanner@1.4.26
jobs:
  test:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test
      
  build_docker:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup common environment variables
          command: |
            echo 'export FULL_IMAGE_NAME="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${AWS_RESOURCE_NAME_PREFIX}:${CIRCLE_SHA1}"' >> $BASH_ENV
      - run: 'docker build -t circle_docker_test:latest .'
      # Could push up to a registry at this stage
      - run: 'mkdir docker_image && docker save -o docker_image/circleci_built_container.tar circle_docker_test:latest'
      - store_artifacts:
          path: docker_image/circleci_built_container.tar
          destination: circleci_built_container.tar
      - persist_to_workspace:
          root: .
          paths:
            - docker_image

# Manually setup as orb won't work with the unpushed image.
# TODO: Create custom Docker image for the scanner (using https://github.com/ovotech/clair-scanner-docker/blob/master/Dockerfile) rather than using theirs
  vuln_scan:
    docker:
      - image: ovotech/clair-scanner@sha256:6fd950030d971317b3b8ee5efcc45f0c3cf624b68cf741c83f787a9dde9917cc
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: workspace
      - run:
          name: Load image
          command: |
            docker load --input workspace/docker_image/circleci_built_container.tar
      - run:
          name: Setup common environment variables
          command: |
            echo 'export FULL_IMAGE_NAME="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${AWS_RESOURCE_NAME_PREFIX}:${CIRCLE_SHA1}"' >> $BASH_ENV;
            echo 'export THRESHOLD="High"' >> $BASH_ENV;
            echo 'export IMAGE="circle_docker_test:latest"' >> $BASH_ENV;
      - run:
          name: "Vulnerability scan"
          command: |
            #!/usr/bin/env bash
            
            REPORT_DIR=workspace/clair-reports
            mkdir $REPORT_DIR
            
            DB=$(docker run -p 5432:5432 -d arminc/clair-db:latest)
            CLAIR=$(docker run -p 6060:6060 --link $DB:postgres -d arminc/clair-local-scan:latest)
            CLAIR_SCANNER=$(docker run -v /var/run/docker.sock:/var/run/docker.sock -d ovotech/clair-scanner@sha256:6fd950030d971317b3b8ee5efcc45f0c3cf624b68cf741c83f787a9dde9917cc tail -f /dev/null)
            
            clair_ip=$(docker exec -it $CLAIR hostname -i | grep -oE '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+')
            scanner_ip=$(docker exec -it $CLAIR_SCANNER hostname -i | grep -oE '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+')
            
            if [ -n $WHITELIST ]; then
                cat "$WHITELIST"
                docker cp "$WHITELIST" $CLAIR_SCANNER:/whitelist.yml
            
                WHITELIST="-w /whitelist.yml"
            fi
            
            EXIT_STATUS=0
            
            function scan() {
                local image=$1
                mkdir -p "$REPORT_DIR/$(dirname $image)"
            
                docker pull "$image"
            
                if ! docker exec -it $CLAIR_SCANNER clair-scanner --ip ${scanner_ip} --clair=http://${clair_ip}:6060 -t "$THRESHOLD" --report "/report.json" $WHITELIST "$image"; then
                    EXIT_STATUS=1
                fi
            
                docker cp "$CLAIR_SCANNER:/report.json" "$REPORT_DIR/${image}.json"
            }
            
            if [ -n "$IMAGE_FILE" ]; then
                images=$(cat "$IMAGE_FILE")
                for image in $images; do
                    scan $image
                done
            else
                scan "$IMAGE"
            fi
            
            if [ "$FAIL_ON_VULN" == "false" ]; then
                exit 0
            else
                exit $EXIT_STATUS
            fi
        

  deploy_docker_aws:
    docker:
      - image: circleci/python:3.6.1
    environment:
      AWS_DEFAULT_OUTPUT: json
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: workspace
      - aws-cli/install
      - aws-cli/configure:
          aws-access-key-id: "$AWS_ACCESS_KEY_ID"
          aws-region: "$AWS_DEFAULT_REGION"
      - run:
          name: Load image
          command: |
            docker load --input workspace/docker_image/circleci_built_container.tar
      - run:
          name: Setup common environment variables
          command: |
            echo 'export FULL_IMAGE_NAME="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${AWS_RESOURCE_NAME_PREFIX}:${CIRCLE_SHA1}"' >> $BASH_ENV
            echo 'export LATEST_IMAGE_NAME="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${AWS_RESOURCE_NAME_PREFIX}:latest"' >> $BASH_ENV
      - run:
          name: Tag image correctly
          command: |
            docker tag circle_docker_test:latest $FULL_IMAGE_NAME
      - run:
          name: Tag image with :latest as well
          command: |
            docker tag $FULL_IMAGE_NAME $LATEST_IMAGE_NAME
      - run:
          name: Push image tags
          command: |
            eval $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
            docker push $FULL_IMAGE_NAME
            docker push $LATEST_IMAGE_NAME

  deploy_docker_azure:
    executor: azure-cli/default
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: workspace
      - azure-cli/install
      - azure-cli/login-with-service-principal
      - run:
          name: Load image
          command: |
            docker load --input workspace/docker_image/circleci_built_container.tar
      - run:
          name: Setup common environment variables
          command: |
            echo 'export FULL_IMAGE_NAME="phil30516test.azurecr.io/circleci:${CIRCLE_SHA1}"' >> $BASH_ENV
      - run:
          name: Tag image correctly
          command: |
            docker tag circle_docker_test:latest $FULL_IMAGE_NAME
      - run:
          name: Push image
          command: |
            eval $(az acr login --name phil30516test)
            docker push $FULL_IMAGE_NAME

workflows:
  version: 2
  all:
    jobs:
      - test
      - build_docker:
          requires:
            - test
      - vuln_scan:
          requires:
            - test
            - build_docker
      - deploy_docker_aws:
          requires:
            - build_docker
            - vuln_scan
      - deploy_docker_azure:
          requires:
            - build_docker
            - vuln_scan

