# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test
      
  build_docker:
    machine: true
    steps:
      - checkout
      - run: docker build -t circleci_built_container
      # Could push up to a registry at this stage
      - run: docker save -o circleci_built_container.tar circleci_built_container
      - store_artifacts:
          path: circleci_built_container.tar
          destination: circleci_built_container.tar

workflows:
  version: 2
  all:
    jobs:
      - test
      - build_docker:
          requires:
            - test
